# Generated by Django 4.1.6 on 2023-05-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('prescription', '0001_initial'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'License Holder',
                'verbose_name_plural': 'License Holders',
            },
        ),
        migrations.CreateModel(
            name='LicenseIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.address')),
            ],
            options={
                'verbose_name': 'License Issuer',
                'verbose_name_plural': 'License Issuers',
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('expiration_date', models.DateField()),
                ('batch_number', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medicine.marketablemedicine')),
            ],
            options={
                'verbose_name': 'Medicine Batch',
                'verbose_name_plural': 'Medicine Batches',
            },
        ),
        migrations.CreateModel(
            name='PackagingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
                ('license_holder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.licenseholder')),
                ('license_issuer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.licenseissuer')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreStockQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine_batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.medicinebatch')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.store')),
            ],
            options={
                'verbose_name': 'Store Stock Quantity',
                'verbose_name_plural': 'Store Stock Quantities',
            },
        ),
        migrations.CreateModel(
            name='MedicineBatchSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.bill')),
                ('medicine_batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.medicinebatch')),
            ],
            options={
                'verbose_name': 'Medicine Batch Sale',
                'verbose_name_plural': 'Medicine Batch Sales',
            },
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.packagingunit'),
        ),
        migrations.AddField(
            model_name='licenseholder',
            name='license_issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.licenseissuer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.store'),
        ),
        migrations.AddField(
            model_name='bill',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prescription.visit'),
        ),
    ]
