# Generated by Django 4.1.6 on 2023-05-20 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('address', '0001_initial'),
        ('patient', '0001_initial'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='address.address')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prescription.dosage')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medicine.marketablemedicine')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prescription.visit')),
            ],
        ),
    ]
