# Generated by Django 4.1.6 on 2023-05-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('address', '0001_initial'),
        ('doctor', '0001_initial'),
        ('medicine', '0004_rename_formulamedicine_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.address')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='doctor.doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medicine.marketablemedicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='patient.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prescription.visit')),
            ],
        ),
    ]
