# Generated by Django 4.1.6 on 2023-05-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_visit_created_at_visit_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
    ]
