# Generated by Django 4.1.6 on 2023-05-13 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_remove_prescription_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prescription.dosage'),
        ),
    ]
