# Generated by Django 4.1.6 on 2023-05-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
