# Generated by Django 4.1.6 on 2023-02-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('TAB', 'Tablet'), ('CAP', 'Capsule'), ('SYP', 'Syrup'), ('INJ', 'Injectable'), ('OINT', 'Ointment'), ('PWDR', 'Powder'), ('DROP', 'Drops'), ('INV', 'Intravenous'), ('INH', 'Inhaler'), ('GEL', 'Gel'), ('LOT', 'Lotion'), ('SPRY', 'Spray'), ('PAST', 'Paste'), ('OTH', 'Other')], default='OTH', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.marketer')),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WW', 'Weight to Weight'), ('WV', 'Weight to Volume'), ('VW', 'Volume to Weight'), ('VV', 'Volume to Volume')], default='WW', max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('MG', 'Milligram'), ('GM', 'Gram'), ('KG', 'Kilogram'), ('ML', 'Milliliter'), ('L', 'Liter'), ('OTH', 'Other')], default='MG', max_length=3)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.molecule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='medicinecomposition',
            constraint=models.UniqueConstraint(fields=('medicine', 'type'), name='unique_composition_type'),
        ),
    ]
