# Generated by Django 4.1.6 on 2023-03-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('TAB', 'Tablet'), ('CAP', 'Capsule'), ('SYP', 'Syrup'), ('INJ', 'Injectable'), ('OINT', 'Ointment'), ('PWDR', 'Powder'), ('DROP', 'Drops'), ('INV', 'Intravenous'), ('INH', 'Inhaler'), ('GEL', 'Gel'), ('LOT', 'Lotion'), ('SPRY', 'Spray'), ('PAST', 'Paste'), ('OTH', 'Other')], default='OTH', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketableMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.marketer')),
            ],
        ),
        migrations.AlterField(
            model_name='medicinecomposition',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.marketablemedicine'),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
