# Generated by Django 4.1.6 on 2023-03-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_medicinecomposition_formula_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinecomposition',
            old_name='formula_medicine',
            new_name='formula',
        ),
    ]
