# Generated by Django 4.1.6 on 2023-03-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_remove_medicinecomposition_unique_composition_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicinecomposition',
            name='unique_composition_type',
        ),
        migrations.AddConstraint(
            model_name='medicinecomposition',
            constraint=models.UniqueConstraint(fields=('formula_medicine', 'molecule', 'type', 'quantity', 'unit'), name='unique_composition_type'),
        ),
    ]
