# Generated by Django 4.1.6 on 2023-03-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_remove_medicinecomposition_unique_composition_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicinecomposition',
            name='unique_composition_type',
        ),
    ]
